### ISSUE TITLE
Feedback for “Server Exports” On Docs

### ISSUE THREAD

**Issue by NobodyDeveloper** [Qbox-project/qbox-project.github.io#24]
GetPlayer should return all of it's attributes, Instead of saying
Returns "Player?" , Should have information on the table

**Comment by D4isDAVID** [comment]
At the top of the Server Exports page, it says the following:
> Some of these exports use custom types. You can learn more about those in the Types section of this resource.

There is a [Player page](https://docs.qbox.re/resources/qbx_core/types/player) available in the Types section for qbx_core.
