### ISSUE TITLE
Weapon attachment question

### ISSUE THREAD

**Issue by mutedavinci** [Qbox-project/qbox-project.github.io#41]
So, we have some custom weapons, and we are trying to figure out where we have to define their attachments. On your "weapons" page there is a minimal amount of information regarding this topic. We've got them all in the items lua, we've tried placing them independently in the weapons lua, so on and so forth, I would GREATLY appreciate it if you guys could reach out and let me know how exactly to do this. Searching the default repo that is given when you setup a base qbox server the attachments for the default weapons are only defined in the items lua after doing a search, and they seem to work just fine.

**Comment by solareon** [comment]
These are all defined in ox_inventory/data/weapons.lua. The weapons.lua has a note at the top pointing you to the correct location

**Comment by mutedavinci** [comment]
> These are all defined in ox_inventory/data/weapons.lua. The weapons.lua has a note at the top pointing you to the correct location

Thank you! I do not see a note anywhere in that section, but we did figure it out. You guys went into craaaaazy detail with how this framework is built btw, It's an amazing change.
